### ISSUE TITLE
General TODO List.

### ISSUE THREAD

**Issue by Thutmose** [Thutmose/Pokecube#145]
# General list of things TODO (no specific order)
## Pokecube Core
- [ ] Sleeptalk/Snore
- [ ] Check that shadow mobs still work
- [ ] Check Recipe Book entries for recipes.
- [ ] IPokemobUsable interaction for things with "pokebloc" tag (revives at first)
- [ ] Check single player riding a Pokemob across dimensions - Possibly fixed?
- [ ] ingrain should prevent movement
- [ ] related to ^ add AIRoutine/state for disabling combat movement - Partially implemented
- [ ] Swimming mobs shouldn't slow down when pathing above water.
- [ ] use sendStatusMessage() to add tooltip like messages.
- [ ] Pokemob look vec in certain client rendering things
- [ ] Dimension Specific configs for worldgen. - 1.12.2
- [ ] Generic block denial message shouldn't be for secret bases only...
- [ ] Health of mobs with 147 max hp when dead... - Need to reproduce this somehow...

## Pokecube Addons
- [ ] Worldgen for gyms (need some sample builds)
- [ ] Allow AFA to preset animations and paths for pokemobs to move in.
- [ ] Applied Energistics meteor support for subbiomes
- [ ] Bag inventory from inside pokemob inventory.

## Pokecube Mobs
- [ ] Fix Zygarde hitbox
- [ ] Add shadow mobs (maybe make a seperate submod for this
- [ ] magcargo head childing

## Misc
- [ ] Check performance of having bunches of if(stuff) vs using lablels and break statements.
- [ ] Elytra in Back slot for Thut Wearables.
- [ ] Pokecube Alternative right click to use revives.
- [ ] Check to see if anywhere on the AI thread it triggers loading mobs, this shouldn't happen.

## Pokeplayer
- [ ] Check packets in pokeplayer.

Comment anything you think should go on here, and I might add them at my discretion

**Comment by Karagra** [comment]
- [x] Daycare block to leave Pokemon in sit position to gain Exp over time.

**Comment by jochuan** [comment]
that daycare idea is cool but instead of sitting next to it the pokemon should be placed inside it and the only way to remove it should be by trading it for emeralds equivalent to the levels that the pokemon grew

**Comment by Thutmose** [comment]
hmm, maybe instead of placing it inside, maybe have the daycare block consume emeralds to run?  I can make it say have 1 inventory slot to put emeralds in, and it uses them up as it gives exp

**Comment by jochuan** [comment]
but that will make it work with a lot of pokemons with the price of one ?

**Comment by Thutmose** [comment]
nope, I will have it consume an emerald or shard whenever it applies exp to the mob, so if you have multiple pokemobs nearby, it will use emeralds faster

**Comment by jochuan** [comment]
other thing that should be added to the todo list is gyms, poke seals and the shadow stuff

**Comment by jochuan** [comment]
Also when you add the gyms i think that you should make a way of one player to only be able to carry 6 pokemons in the inventory because without that, the battle against the gyms leaders will be too easy since you can fill your inventory with a lot of different pokemons.You will only be able to carry 6 pokemons but you can have as  many pokemon as you want outside of the pokeball for guarding purposes.I think that one easy way do that is by adding another gui next to the main inventory gui with only 6 slots and the pokeballs with pokemons should be only placed on it and when you want to use the pokemon you should press some button to switch the minecraft hotbar gui to the gui with pokemons so you can use them.

**Comment by Thutmose** [comment]
I am working on an addon for Karagra's server which does the 6 pokemob thing.

I don't plan to integrate this into the main pokecube mods, mainly as I prefer the balance due to inventory restraints, but it will be released on curse at some point.

**Comment by jochuan** [comment]
make the chances of a critical capture occurring scale with the number of pokemon caught and add a sound to it if it dont have 
http://bulbapedia.bulbagarden.net/wiki/Catch_rate

**Comment by Thutmose** [comment]
the sound has been re-added, just haven't got it relseased yet, oh, you mean for critical capture, no sound for that yet

**Comment by jochuan** [comment]
and would be cool if you could add sound for super effective hits and not effective hits that would help a lot since the battle happens fast

**Comment by jochuan** [comment]
A way to track the legendary roaming pokemon, in all the pokemons games after you have seen the legendary pokemon you could track where it is using the pokedex since that is too hard to make in minecraft, you would receive a message saying that the pokemon is near you similar to pixelmon but for that message to appear you would first need to have fought that pokemon so for example when you kill a suicune that you wanted to caught you will receive a message saying that suicune is near you when another suicune spawn

**Comment by Thutmose** [comment]
problem is that when a legendary spawns, it spawns near you, you will see it, you don't need something that tells you that it spawns.

**Comment by jochuan** [comment]
but how many blocks away from you he can spawn ? 32? if you are underground or in a forest you may not see it and it may kill you and this message can be a way to find him again if you dont have a minimap mod also i think that those legendaries should walk more like a real roaming pokemon instead of staying in the same biome walking in circles like all vanilla mobs

**Comment by jochuan** [comment]
i dont know if this already has been added since i did not played this mod for two months by now but did you gonna add a GUI to show what a move does and what is it power and accuracy when you learn it and the same for  already learned moves, that would help a lot when you gonna delete one move to learn other

**Comment by Thutmose** [comment]
it already shows what power the move has, it has always shown that in the pokedex (the number on the right of there it has the move's name), I am not sure where I should put a thing to show stuff like accuracy, status, effect, etc though.

**Comment by jochuan** [comment]
i think that could be put on a window when you houver your mouse on the move, the same thing that happens when you hover your mouse on a item in the inventory, this  information would be a lot useful
